### ISSUE TITLE
Unable to load calendar

### ISSUE THREAD

**Issue by dkNeumann** [J-Lindvig/Flagdays_DK#3]
Hello,
Recently the integration stopped working, I get the following the system log:

Logger: homeassistant.components.sensor
Source: custom_components/flagdays_dk/sensor.py:70
Integration: Sensor (documentation, issues)
First occurred: 16.24.09 (2 occurrences)
Last logged: 16.24.09

Error adding entities for domain sensor with platform flagdays_dk
Error while setting up flagdays_dk platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/flagdays_dk/sensor.py", line 70, in state
    return self._nextFlagDay.getDays()
AttributeError: 'NoneType' object has no attribute 'getDays'

I'm on:
Home Assistant 2022.12.8
Supervisor 2022.12.1
Operating System 9.4
Brugerfladeversion: 20221213.1 - latest

I have tried to remove the integration and the re-install with the default settings, but no luck.

**Comment by J-Lindvig** [comment]
Could be an issue occuring when the official list is empty....
https://www.justitsministeriet.dk/temaer/flagning/flagdage/

I will looking into the matter when possible.

**Comment by dkNeumann** [comment]
Seems very possible, tried to look at justitsministeriet.dk and they have not updated the list, however it exists and can be reached specifying the year, as follows:
https://www.justitsministeriet.dk/temaer/flagning/flagdage/flagdage-2023/
Regards,
Henrik

**Comment by J-Lindvig** [comment]
Thank you for the contribution - I am a little preoccupied these days. Will update the integration "next year".... ;-)

**Comment by dkNeumann** [comment]
I can comfirm, that if I change the URL in the const.py file it works.
Happy New Year to you :-)

**Comment by J-Lindvig** [comment]
Wow, thank you for your effort....

**Comment by J-Lindvig** [comment]
HelloA completely new and 100% rewritten version is soon available.The new version does not rely on webscraping of the flagdays. The calculation of sunrise and sunset is also done locally.I need a few days for final testing before release - maybe you would like to test it?/Jacob11. jan. 2023 18.30 skrev dkNeumann ***@***.***>:
I now have another problem loading the add-on:
My logs have this:
Logger: homeassistant.setup
Source: custom_components/flagdays_dk/init.py:39
Integration: flagdays_dk (documentation, issues)
First occurred: 18.26.06 (1 occurrences)
Last logged: 18.26.06
Error during setup of component flagdays_dk
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
result = await task
File "/config/custom_components/flagdays_dk/init.py", line 39, in async_setup
flags = config[DOMAIN].get(CONF_FLAGS, [DEFAULT_FLAG])
AttributeError: 'NodeListClass' object has no attribute 'get'

**Comment by J-Lindvig** [comment]
A pre-release version is available here: https://my.ocloud.dk/index.php/s/pNDJyNZd9D5FKFY

`flagdays_dk:
  # Optional entries
  offset: 5 # New name
  flagdays:
    - name: Jolly Roger Memorial Day
      flag: Jolly Roger
      date: 10-06-1975

    - name: Copenhagen Pride Month
      flag: Pride
      date: 01-08
      date_end: 31-08

    - name: Tim Berners Lee Birthday
      date: 08-06-1955
      priority: 2 # 0 is highest priority

    - name: Ada Lovelace Birthday
      date: 10-12-1815

**Comment by dkNeumann** [comment]
I still get an error:

Logger: homeassistant.setup
Source: custom_components/flagdays_dk/__init__.py:28
Integration: flagdays_dk ([documentation](https://github.com/J-Lindvig/Flagdays_DK), [issues](https://github.com/J-Lindvig/Flagdays_DK/issues))
First occurred: 17.01.24 (1 occurrences)
Last logged: 17.01.24

Error during setup of component flagdays_dk
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/flagdays_dk/__init__.py", line 28, in async_setup
    flagdays.addCustom(config[DOMAIN].get(CONF_FLAGDAYS))
AttributeError: 'NodeListClass' object has no attribute 'get'

**Comment by J-Lindvig** [comment]
Try putting just flagdays: into the config.

It is a work in progress, but I believe that I will have a working version ready in a few days.

**Comment by J-Lindvig** [comment]
````Yaml
flagdays_dk:
````

**Comment by J-Lindvig** [comment]
Fixed in v.3.0.

**Comment by dkNeumann** [comment]
Hi,
Still the same issue:

Logger: homeassistant.setup
Source: custom_components/flagdays_dk/__init__.py:63
Integration: flagdays_dk ([documentation](https://github.com/J-Lindvig/Flagdays_DK), [issues](https://github.com/J-Lindvig/Flagdays_DK/issues))
First occurred: 16.12.06 (1 occurrences)
Last logged: 16.12.06

Error during setup of component flagdays_dk
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/flagdays_dk/__init__.py", line 63, in async_setup
    for customFlagday in config[DOMAIN].get(CONF_FLAGDAYS):
TypeError: 'NoneType' object is not iterable

I'm running v3.0.1. Have the one line as config.

**Comment by J-Lindvig** [comment]
Oh, shit - I see it too with only the "one-liner"....

**Comment by J-Lindvig** [comment]
I have fixed, but unable to upload to github at the moment.

**Comment by J-Lindvig** [comment]
Uploaded v3.0.2 with a fix.
